import 'dart:convert';

import 'package:http/http.dart' as http;

class GeminiAPI {
  // Create a header
  static Future<Map<String, String>> getHeader() async {
    return {
      'Content-Type': 'application/json',
    };
  }

  // Send request to Gemini API
  static Future<String> getGeminiData(String message, String hiddenMessage) async {
    try {
      String apiKey = 'AIzaSyCuynSg-DJKEx1nDwU5ihxJtKMCpNzC7lo'; // Put your API Key here
      final header = await getHeader();

      final Map<String, dynamic> requestBody = {
        'contents': [
          {
            'parts': [
              {
                'text': message,
              },
              {
                'text': hiddenMessage, // Include the hidden message
              }
            ]
          }
        ],
        'generationConfig': {
          'temperature': 0.8, // It may vary from 0 to 1
          'maxOutputTokens': 1000, // Max tokens to generate result
        }
      };

      String url =
          'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?key=$apiKey';

      // Send the request
      var response = await http.post(
        Uri.parse(url),
        headers: header,
        body: jsonEncode(requestBody),
      );

      print(response.body); // Print response body for debugging

      if (response.statusCode == 200) {
        // 200 for success response
        var jsonResponse = jsonDecode(response.body) as Map<String, dynamic>;
        return jsonResponse['candidates'][0]['content']['parts'][0]['text'];
        // Return the result generated by Gemini
      } else {
        return '';
      }
    } catch (e) {
      print("Error: $e");
      return '';
    }
  }
}
